name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Cordova
      run: npm install -g cordova

    - name: Build App
      run: |
        cordova create app com.sirsalman.myapp MyApp
        cp index.html app/www/index.html
        cd app
        cordova platform add android
        cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/platforms/android/app/build/outputs/apk/debug/*.apk
